// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAuLNwPrtGyU0di6BKRzzp1UGrGFQruQ',
    appId: '1:1067262658758:web:0219c9ab64917d562eafc7',
    messagingSenderId: '1067262658758',
    projectId: 'aegis-ai-omni',
    authDomain: 'aegis-ai-omni.firebaseapp.com',
    storageBucket: 'aegis-ai-omni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOk5yd4gWgG-nbadRtE2qVD8w2i4F4zA',
    appId: '1:1067262658758:android:bada23d83b2766db2eafc7',
    messagingSenderId: '1067262658758',
    projectId: 'aegis-ai-omni',
    storageBucket: 'aegis-ai-omni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldTUt6J20nY--_W_A4XEez_Co8VtCXeM',
    appId: '1:1067262658758:ios:e283ef7be104ab172eafc7',
    messagingSenderId: '1067262658758',
    projectId: 'aegis-ai-omni',
    storageBucket: 'aegis-ai-omni.firebasestorage.app',
    iosBundleId: 'com.aegis.omni',
  );

}